field: 3cbe8045-904b-49bb-ac50-4926692bbaaf
fieldLayouts:
  fe7e1ecb-e18d-4099-b14b-a9e74ec95f95:
    tabs:
      -
        elements:
          -
            fieldUid: c4abaacd-d898-499d-a4b2-c07043287716
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  c4abaacd-d898-499d-a4b2-c07043287716:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: heading
name: heading
sortOrder: 1
