field: 3cbe8045-904b-49bb-ac50-4926692bbaaf
fieldLayouts:
  35c8ef8c-7749-4feb-b978-014c2520b0df:
    tabs:
      -
        elements:
          -
            fieldUid: 87d40e09-ebd6-43fd-a04c-f10c36136d34
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  87d40e09-ebd6-43fd-a04c-f10c36136d34:
    contentColumnType: text
    fieldGroup: null
    handle: links
    instructions: ''
    name: Links
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: link
name: link
sortOrder: 3
