field: 80672d7d-1690-47a4-904e-14e353770526
fieldLayouts:
  cdb435cb-31d0-4ec3-a596-acb75043007c:
    tabs:
      -
        elements:
          -
            fieldUid: 6dd039e4-fb62-4d70-ada3-4f6fce6921d8
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4664af46-0a8c-47d6-ac5f-f116da7c7104
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4664af46-0a8c-47d6-ac5f-f116da7c7104:
    contentColumnType: string
    fieldGroup: null
    handle: linkDestination
    instructions: ''
    name: 'Link Destination'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  6dd039e4-fb62-4d70-ada3-4f6fce6921d8:
    contentColumnType: text
    fieldGroup: null
    handle: linkText
    instructions: ''
    name: 'Link Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: navLink
name: 'Nav Link'
sortOrder: 1
