field: 0348ab67-1309-4352-b4c7-50d888e4193f
fieldLayouts:
  3244b2f3-7266-4b65-be84-f5d3d93b7735:
    tabs:
      -
        elements:
          -
            fieldUid: ea2653e0-0488-467b-9089-ae51d28f1f33
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 559a17c2-fd93-49ac-b202-3e136746596e
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  559a17c2-fd93-49ac-b202-3e136746596e:
    contentColumnType: string
    fieldGroup: null
    handle: linkDestination
    instructions: ''
    name: 'Link Destination'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  ea2653e0-0488-467b-9089-ae51d28f1f33:
    contentColumnType: text
    fieldGroup: null
    handle: linkText
    instructions: ''
    name: 'Link text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: navLink
name: 'Nav Link'
sortOrder: 1
