fieldLayouts:
  c6646a7e-cb01-4c85-ba32-ab58e713af97:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: 'Page title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 3cbe8045-904b-49bb-ac50-4926692bbaaf
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: pages
hasTitleField: true
name: Pages
section: a33a073b-15ff-49f7-9d47-1e80709c0e74
sortOrder: 1
titleFormat: title
titleTranslationKeyFormat: null
titleTranslationMethod: site
