contentColumnType: string
fieldGroup: 89a801dc-4207-40dc-9685-25404b21694d
handle: about
instructions: ''
name: About
searchable: false
settings:
  contentTable: '{{%matrixcontent_about}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
