contentColumnType: string
fieldGroup: 89a801dc-4207-40dc-9685-25404b21694d
handle: admissions
instructions: ''
name: Admissions
searchable: false
settings:
  contentTable: '{{%matrixcontent_admissions}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
