contentColumnType: string
fieldGroup: 5bcd0203-19a2-4abc-af8a-aef6269e6b40
handle: bodyContent
instructions: ''
name: 'Body Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_bodycontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
