contentColumnType: text
fieldGroup: a0b0d55f-0def-4b56-b114-9c1cafccb382
handle: paragraph2
instructions: ''
name: Paragraph2
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '5'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
