contentColumnType: string
fieldGroup: 89a801dc-4207-40dc-9685-25404b21694d
handle: portal
instructions: ''
name: Portal
searchable: false
settings:
  contentTable: '{{%matrixcontent_portal}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
