enableVersioning: true
handle: aboutalumni
name: AboutAlumni
propagationMethod: all
siteSettings:
  347fb537-1b10-43af-aa22-3b9c7df0448f:
    enabledByDefault: true
    hasUrls: true
    template: about\aboutalumni
    uriFormat: aboutalumni
structure:
  maxLevels: null
  uid: 1e08bfb4-fbc4-43ce-b5ec-ef562201c03d
type: structure
