enableVersioning: true
handle: aboutstaff
name: AboutStaff
propagationMethod: all
siteSettings:
  347fb537-1b10-43af-aa22-3b9c7df0448f:
    enabledByDefault: true
    hasUrls: true
    template: about\aboutstaff
    uriFormat: aboutstaff
structure:
  maxLevels: null
  uid: 3c2c2442-68a2-4a1a-8f05-47b158cac0c6
type: structure
