enableVersioning: true
handle: alumni
name: Alumni
propagationMethod: all
siteSettings:
  347fb537-1b10-43af-aa22-3b9c7df0448f:
    enabledByDefault: true
    hasUrls: true
    template: portal\alumni
    uriFormat: 'portal/alumni/{slug}'
structure:
  maxLevels: null
  uid: 0c41d934-4129-490d-aaf3-6f73fa131818
type: structure
