enableVersioning: true
handle: apply
name: Apply
propagationMethod: all
siteSettings:
  347fb537-1b10-43af-aa22-3b9c7df0448f:
    enabledByDefault: true
    hasUrls: true
    template: admission\apply
    uriFormat: 'admission/apply/{slug}'
structure:
  maxLevels: null
  uid: f5572ce4-8194-4261-a10d-72749856efe7
type: structure
