enableVersioning: true
handle: blogPost
name: 'Blog post'
propagationMethod: all
siteSettings:
  347fb537-1b10-43af-aa22-3b9c7df0448f:
    enabledByDefault: true
    hasUrls: true
    template: blog\_entry
    uriFormat: 'post/{slug}'
type: channel
