enableVersioning: true
handle: galleryView
name: Gallery-view
propagationMethod: all
siteSettings:
  347fb537-1b10-43af-aa22-3b9c7df0448f:
    enabledByDefault: true
    hasUrls: true
    template: gallery-view
    uriFormat: 'gallery-view/{slug}'
type: channel
