enableVersioning: true
handle: gallery
name: Gallery
propagationMethod: all
siteSettings:
  347fb537-1b10-43af-aa22-3b9c7df0448f:
    enabledByDefault: true
    hasUrls: true
    template: gallery
    uriFormat: gallery
type: single
