enableVersioning: true
handle: gallery
name: Gallery
propagationMethod: all
siteSettings:
  347fb537-1b10-43af-aa22-3b9c7df0448f:
    enabledByDefault: true
    hasUrls: true
    template: gallery
    uriFormat: 'gallery/{slug}'
structure:
  maxLevels: null
  uid: 871ab187-3dd1-4a3b-a4bb-9ad59e0451b6
type: structure
