enableVersioning: true
handle: galleryPost
name: 'Gallery Post'
propagationMethod: all
siteSettings:
  347fb537-1b10-43af-aa22-3b9c7df0448f:
    enabledByDefault: true
    hasUrls: true
    template: gallery\_entry
    uriFormat: 'post/{slug}'
type: channel
