enableVersioning: true
handle: greetings
name: Greetings
propagationMethod: all
siteSettings:
  347fb537-1b10-43af-aa22-3b9c7df0448f:
    enabledByDefault: true
    hasUrls: true
    template: about\greetings
    uriFormat: about/greetings
structure:
  maxLevels: null
  uid: 42459457-ab3f-4885-b2f5-03ad2e8972e7
type: structure
