enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  347fb537-1b10-43af-aa22-3b9c7df0448f:
    enabledByDefault: true
    hasUrls: true
    template: home
    uriFormat: __home__
type: single
