enableVersioning: true
handle: mission
name: Mission
propagationMethod: all
siteSettings:
  347fb537-1b10-43af-aa22-3b9c7df0448f:
    enabledByDefault: true
    hasUrls: true
    template: about\mission
    uriFormat: mission
structure:
  maxLevels: null
  uid: 7da97827-5072-4f9b-bab2-ed056930fb46
type: structure
