enableVersioning: true
handle: newsDetails
name: 'News details'
propagationMethod: all
siteSettings:
  347fb537-1b10-43af-aa22-3b9c7df0448f:
    enabledByDefault: true
    hasUrls: true
    template: news-details
    uriFormat: 'news-details/{slug}'
type: channel
