enableVersioning: true
handle: pages
name: Pages
propagationMethod: all
siteSettings:
  347fb537-1b10-43af-aa22-3b9c7df0448f:
    enabledByDefault: true
    hasUrls: true
    template: inside
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 53181348-b700-4aec-8cd7-acec6aed6385
type: structure
