enableVersioning: true
handle: staff
name: Staff
propagationMethod: all
siteSettings:
  347fb537-1b10-43af-aa22-3b9c7df0448f:
    enabledByDefault: true
    hasUrls: true
    template: portal\staff
    uriFormat: 'portal/staff/{slug}'
structure:
  maxLevels: null
  uid: cc3b1844-83ff-42d8-a436-c4eb10308d25
type: structure
